/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import controlador.Conexion;
import controlador.ControladorFicha;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class Fichaevalua extends javax.swing.JInternalFrame {

    /**
     * Creates new form Fichaevalua
     */
    public Fichaevalua() {
        initComponents();
        setModel();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Conexion conectar=new Conexion();
    Connection conectado=(Connection)conectar.conectar();
    PreparedStatement iniciar;
    ResultSet respuesta;
int res;//para escribir
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpracticante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpuntos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtinstructor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpostura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBficha = new javax.swing.JTable();
        btnactualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtobservacion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txttecnica = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtsino = new javax.swing.JTextField();
        txtcinturon = new javax.swing.JTextField();
        btniniciar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtfecha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("FICHA DE EVALUACION ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("PRACTICANTE :");

        txtpracticante.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("CINTURON ACTUAL :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("PUNTUACION :");

        txtpuntos.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("EVALUADO POR:");

        txtinstructor.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtinstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinstructorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("POSTURA :");

        txtpostura.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("RESULTADO :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("TECNICA :");

        TBficha.setBackground(new java.awt.Color(204, 255, 204));
        TBficha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBficha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBfichaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBficha);

        btnactualizar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        txtobservacion.setColumns(20);
        txtobservacion.setRows(5);
        jScrollPane2.setViewportView(txtobservacion);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("OBSERVACIONES :");

        txttecnica.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txttecnica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttecnicaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("CEDULA :");

        txtsino.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtcinturon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        btniniciar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btniniciar.setText("GUARDAR");
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });

        btneliminar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        txtfecha.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel11.setText("FECHA:");

        txtcedula.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtpracticante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtinstructor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txttecnica, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtpostura, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(77, 77, 77)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtsino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcinturon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btniniciar)
                                .addGap(38, 38, 38)
                                .addComponent(btnactualizar)
                                .addGap(61, 61, 61)
                                .addComponent(btneliminar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtpracticante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtcinturon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpostura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtinstructor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txttecnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtpuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btneliminar)
                    .addComponent(btniniciar))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ArrayList<Ficha> listaFicha = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();

    public void setModel() {
        String[] cabecera = {"Nro.", "Practicante", "cedula",
            "Instructor",
            "cinturon",
            "Fecha",
            "Postura", "Tecnica", "Puntuacion", "Resultado", "Observaciones"};
        modelo.setColumnIdentifiers(cabecera);
        TBficha.setModel(modelo);
    }

    public void setDatos() {
        Object[] datosFila = new Object[modelo.getColumnCount()];
        int nro = 1;
        for (Ficha datos : listaFicha) {
            datosFila[0] = nro;
            datosFila[1] = datos.getPracticante();
            datosFila[2] = datos.getCedula();
            datosFila[3] = datos.getInstructor();
            datosFila[4] = datos.getCinturon();
            datosFila[5] = datos.getFecha();
            datosFila[6] = datos.getTecnica();
            datosFila[7] = datos.getConocimiento();
            datosFila[8] = datos.getPuntuacion();
            datosFila[9] = datos.getResultado();
            datosFila[10] = datos.getObservaciones();
            nro++;
            modelo.addRow(datosFila);
        }
    }
    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        Ficha pM = new Ficha(txtpracticante.getText(),
                txtinstructor.getText(),
                txtcinturon.getText(),
                0, Integer.parseInt(txtcedula.getText()),
                Integer.parseInt(txttecnica.getText()),
                Integer.parseInt(txtpostura.getText()),
                Integer.parseInt(txtpuntos.getText()),
                txtsino.getText(),
                txtobservacion.getText(), txtfecha.getText());

        ControladorFicha pC = new ControladorFicha();
        pC.actualizarFicha(pM);
        setDatos();
        limpiarTabla();
        cargarTabla();
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void txttecnicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttecnicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttecnicaActionPerformed

    private void txtinstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinstructorActionPerformed

    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed

        // TODO add your handling code here:
        Ficha pM = new Ficha(txtpracticante.getText(),
                txtinstructor.getText(),
                txtcinturon.getText(),
                0, Integer.parseInt(txtcedula.getText()),
                Integer.parseInt(txttecnica.getText()),
                Integer.parseInt(txtpostura.getText()),
                Integer.parseInt(txtpuntos.getText()),
                txtsino.getText(),
                txtobservacion.getText(), txtfecha.getText());

        ControladorFicha pC = new ControladorFicha();
        pC.crearFicha(pM);
        listaFicha.add(pM);
        setDatos();
        limpiarTabla();
        cargarTabla();
//        limpiarEntradas();
    }//GEN-LAST:event_btniniciarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        int cedula = Integer.parseInt(txtcedula.getText());
        ControladorFicha pC = new ControladorFicha();
        pC.eliminarFicha(cedula);
        limpiarTabla();
        cargarTabla();
        limpiarEntradas();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void TBfichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBfichaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) TBficha.getModel();
        txtcedula.setText(dtm.getValueAt(TBficha.getSelectedRow(), 4).toString());
        txtcinturon.setText(dtm.getValueAt(TBficha.getSelectedRow(), 2).toString());
        txtfecha.setText(dtm.getValueAt(TBficha.getSelectedRow(), 5).toString());
        txtinstructor.setText(dtm.getValueAt(TBficha.getSelectedRow(), 3).toString());
        txtobservacion.setText(dtm.getValueAt(TBficha.getSelectedRow(), 10).toString());
        txtpostura.setText(dtm.getValueAt(TBficha.getSelectedRow(), 7).toString());
        txtpracticante.setText(dtm.getValueAt(TBficha.getSelectedRow(), 1).toString());
        txtpuntos.setText(dtm.getValueAt(TBficha.getSelectedRow(), 8).toString());
        txtsino.setText(dtm.getValueAt(TBficha.getSelectedRow(), 9).toString());
        txttecnica.setText(dtm.getValueAt(TBficha.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_TBfichaMouseClicked
    private void limpiarTabla() {
        int a = modelo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

     private void cargarTabla() {
    ControladorFicha DF = new ControladorFicha();
    ArrayList<Object[]> lista = DF.datosFicha();
    limpiarTabla();
    for (Object[] filas : lista) {
        // Convertir los IDs a nombres
        filas[1] = NombrePracticante((int) filas[1]);
        filas[3] = NombreInstructor((int) filas[3]);
        filas[4] = NombreCinturon((int) filas[4]);
        modelo.addRow(filas);
    }
    // Establecer el modelo de la tabla fuera del bucle for
    TBficha.setModel(modelo);
}


private String NombrePracticante(int idPracticante) {
    String nombrePracticante = "";
    try {
        String SQL = "SELECT NOMBRE FROM PRACTICANTE WHERE ID_PRACTICANTE = ?";
        iniciar = conectado.prepareStatement(SQL);
        iniciar.setInt(1, idPracticante);
        respuesta = iniciar.executeQuery();
        if (respuesta.next()) {
            nombrePracticante = respuesta.getString("NOMBRE");
        }
        iniciar.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al obtener el nombre del practicante: " + ex.getMessage());
    }
    return nombrePracticante;
}

private String NombreInstructor(int idInstructor) {
    String nombreInstructor = "";
    try {
        String SQL = "SELECT NOMBRE_INS FROM INSTRUCTORES WHERE ID_INSTRUCTOR = ?";
        iniciar = conectado.prepareStatement(SQL);
        iniciar.setInt(1, idInstructor);
        respuesta = iniciar.executeQuery();
        if (respuesta.next()) {
            nombreInstructor = respuesta.getString("NOMBRE_INS");
        }
        iniciar.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al obtener el nombre del instructor: " + ex.getMessage());
    }
    return nombreInstructor;
}

private String NombreCinturon(int idCinturon) {
    String nombreCinturon = "";
    try {
        String SQL = "SELECT COLOR FROM CINTURON WHERE ID_CINTURON = ?";
        iniciar = conectado.prepareStatement(SQL);
        iniciar.setInt(1, idCinturon);
        respuesta = iniciar.executeQuery();
        if (respuesta.next()) {
            nombreCinturon = respuesta.getString("COLOR");
        }
        iniciar.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error al obtener el nombre del cinturón: " + ex.getMessage());
    }
    return nombreCinturon;
}

    public void limpiarEntradas() {
        txtpracticante.setText("");
        txtcedula.setText("");
        txtcinturon.setText("");
        txtfecha.setText("");
        txtinstructor.setText("");
        txtobservacion.setText("");
        txtpostura.setText("");
        txtpuntos.setText("");
        txtsino.setText("");
        txttecnica.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBficha;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btniniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcinturon;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtinstructor;
    private javax.swing.JTextArea txtobservacion;
    private javax.swing.JTextField txtpostura;
    private javax.swing.JTextField txtpracticante;
    private javax.swing.JTextField txtpuntos;
    private javax.swing.JTextField txtsino;
    private javax.swing.JTextField txttecnica;
    // End of variables declaration//GEN-END:variables
}
